micronaut:
  application:
    name: cassandraNative
cassandra:
  default:
    clusterName: '"myCluster"'
    contactPoint: '"localhost"'
    port: 9042
    maxSchemaAgreementWaitSeconds: 20
    ssl: true
